###Product Index
GET http://localhost:3000/products

###Product Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Paco Robbanne Invictus aqua",
  "price": 85,
  "image_url":"https://m.media-amazon.com/images/I/51gAbGPRncL._SL1000_.jpg",
  "description": "Invictus is Latin for “unconquered.” The speaker in the poem proclaims his strength in the face of adversity: My head is bloody, but unbowed.... I am the master of my fate; I am the captain of my soul."
}
###Product Show
GET http://localhost:3000/products/2

###Product update
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
  "name": "invictus aqua legends"
}
### Product Delete
DELETE http://localhost:3000/products/8

###Supplier Index
GET http://localhost:3000/suppliers

###Supplier Create
POST http://localhost:3000/suppliers
Content-Type: application/json


###Supplier Show
GET http://localhost:3000/suppliers/2

###Supplier update
PATCH http://localhost:3000/suppliers/3
Content-Type: application/json

### Supplier Delete
DELETE http://localhost:3000/suppliers/4

### Image Index
GET http://localhost:3000/images

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Danny",
  "email": "danny@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}
### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}